### PR TITLE
folder structure refactor

### PR DESCRIPTION
**Pull request by JanSmrcka**
Refaktor struktury složek @noobadmin. Mrkni na to jestli ti to dává takhle smysl.
Díky.

### CODE REVIEW

**Comment by JanSmrcka** [comment]
těch testů si nevšímej to opravím pak s tím loginem, ale chtěl sem to pak dělat nad finálni folder strukturou

**Review by noobadmin — COMMENTED** [review]
Nice! Look definitely quite a bit simpler now..

Nevertheless, maybe some of the subfolders in /components could be removed as well? e.g. the app-loader component could sit directly in /components since it's simple enough to be contained within a single file and probably will even stay this way.

I neither think we'd need the extra seperation of /ui and /layout.

**Comment by JanSmrcka** [comment]
Closes #88

**Review by noobadmin — APPROVED** [review]
👍🏼 Let's leave it like that for now. We'll see how it works for us and come back to it if needed.

**Pull request merged**
